# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 587709d3f259a0b00e7d137303168112b829337bf9d56f05d91bd18d4074553376565de2d12bd87f0a84c6ae6b5b19bd789571c45936036fa9c6c4a316d9da1e

test:
  secret_key_base: d799efbe498f70c50c908284dbcf18e0e55815f20f04c86dd2a161192ee9be3e063c3a98d809850bf54658ea730776b59c479cc941a18ff74e02194f9d2a0c1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
